services:
  php:
    hostname: ${APP_CONTAINER:-php_cms}
    build: docker/php/.
    image: ${APP_CONTAINER:-php_cms}:apache
    container_name: ${APP_CONTAINER:-php_cms}
    restart: unless-stopped
    environment:
      TZ: Europe/Amsterdam
    volumes:
      - ./:/var/www/html
    networks:
      - docker_server_caddy
      - docker_server_database

networks:
  docker_server_caddy:
    external: true
  docker_server_database:
    external: true
